# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sD7tFZVN1wO9p1alkyKXBxlGpVlD9Uf5
"""

# Dosya işlemleri için open fonksiyonunu kullanacağız
# XOR işlemi için basit bir anahtar belirleyeceğiz

# Kullanıcıdan giriş dosyasının adını alıyoruz
input_file = input("Şifrelenecek dosyanın adını girin (örnek: metin.txt): ")

# Kullanıcıdan şifreli dosya adını alıyoruz
output_file = input("Şifrelenmiş dosyanın kaydedileceği isim (örnek: sifreli.txt): ")

# XOR için kullanılacak anahtar karakter
key = 123  # Sabit bir sayı, istediğin bir sayı olabilir

# Giriş dosyasını okuma, çıkış dosyasını yazma modunda açıyoruz
with open(input_file, "r", encoding="utf-8") as infile, open(output_file, "w", encoding="utf-8") as outfile:
    # Dosyayı satır satır okuyoruz
    for line in infile:
        encrypted_line = ""
        # Her karaktere XOR uyguluyoruz
        for char in line:
            # ord(): karakteri ASCII sayıya çevirir
            # chr(): sayıyı tekrar karaktere çevirir
            encrypted_char = chr(ord(char) ^ key)
            encrypted_line += encrypted_char
        # Şifreli satırı dosyaya yaz
        outfile.write(encrypted_line)

print(f" Dosya '{output_file}' olarak şifrelendi.")

# Dosya işlemleri için open fonksiyonunu kullanacağız
# XOR işlemi için basit bir anahtar belirleyeceğiz

# Kullanıcıdan giriş dosyasının adını alıyoruz
input_file = input("Şifrelenecek dosyanın adını girin (örnek: metin.txt): ")

# Kullanıcıdan şifreli dosya adını alıyoruz
output_file = input("Şifrelenmiş dosyanın kaydedileceği isim (örnek: sifreli.txt): ")

# XOR için kullanılacak anahtar karakter
key = 123  # Sabit bir sayı, istediğin bir sayı olabilir

# Giriş dosyasını okuma, çıkış dosyasını yazma modunda açıyoruz
with open(input_file, "r", encoding="utf-8") as infile, open(output_file, "w", encoding="utf-8") as outfile:
    # Dosyayı satır satır okuyoruz
    for line in infile:
        encrypted_line = ""
        # Her karaktere XOR uyguluyoruz
        for char in line:
            # ord(): karakteri ASCII sayıya çevirir
            # chr(): sayıyı tekrar karaktere çevirir
            encrypted_char = chr(ord(char) ^ key)
            encrypted_line += encrypted_char
        # Şifreli satırı dosyaya yaz
        outfile.write(encrypted_line)

print(f" Dosya '{output_file}' olarak şifrelendi.")

